# Generated by Django 6.1.1 on 2026-09-24 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.CharField(blank=True, max_length=500, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
                ('resolver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_requests',
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_portal_reset_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('OPEN', 'RESOLVED', 'REJECTED'))), name='ck_portal_reset_requests__status_allowed'), models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('resolver__isnull', True), ('status', 'OPEN')), models.Q(('resolved_at__isnull', False), ('resolver__isnull', False), ('status__in', ('RESOLVED', 'REJECTED'))), _connector='OR'), name='ck_portal_reset_requests__resolution_consistent')],
            },
        ),
        migrations.CreateModel(
            name='SupportHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('assigned_support_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_support_handoffs', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='support_handoff', to='conversations.conversation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_support_handoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_handoffs',
                'indexes': [models.Index(fields=['status', 'requested_at'], name='idx_portal_handoffs_queue'), models.Index(fields=['assigned_support_user', 'status', 'requested_at'], name='idx_portal_handoffs_assigned')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('WAITING', 'ASSIGNED', 'RESOLVED', 'CANCELLED'))), name='ck_portal_handoffs__status_allowed'), models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), ('assigned_support_user__isnull', True), ('resolved_at__isnull', True), ('resolved_by__isnull', True), ('status', 'WAITING')), models.Q(('accepted_at__isnull', False), ('assigned_support_user__isnull', False), ('resolved_at__isnull', True), ('resolved_by__isnull', True), ('status', 'ASSIGNED')), models.Q(('accepted_at__isnull', False), ('assigned_support_user__isnull', False), ('resolved_at__isnull', False), ('resolved_by__isnull', False), ('status', 'RESOLVED')), models.Q(('resolved_at__isnull', False), ('status', 'CANCELLED')), _connector='OR'), name='ck_portal_handoffs__lifecycle_consistent')],
            },
        ),
    ]
