BEGIN;

-- Governed knowledge-source registry.
CREATE TABLE rag.sources (
    source_id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    source_type TEXT NOT NULL,
    origin TEXT NOT NULL,
    reference TEXT NOT NULL,
    domain TEXT,
    status TEXT NOT NULL,
    priority SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_sources PRIMARY KEY (source_id)
);

-- Stable current-document identity; historical versions are not modeled.
CREATE TABLE rag.documents (
    document_id UUID NOT NULL DEFAULT gen_random_uuid(),
    source_id UUID NOT NULL,
    document_key TEXT NOT NULL,
    title TEXT NOT NULL,
    document_type TEXT NOT NULL,
    content_checksum TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING',
    last_ingested_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_documents PRIMARY KEY (document_id)
);

-- Current published retrieval units; vector and FTS representations are supplied by the application.
CREATE TABLE rag.chunks (
    chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_id UUID NOT NULL,
    content TEXT NOT NULL,
    chunk_order INTEGER NOT NULL,
    section TEXT,
    content_type TEXT NOT NULL DEFAULT 'TEXT',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    embedding VECTOR(384) NOT NULL,
    search_vector TSVECTOR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_chunks PRIMARY KEY (chunk_id)
);

-- Ingestion provenance and lifecycle records.
CREATE TABLE rag.ingestion_runs (
    ingestion_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id UUID NOT NULL,
    document_id UUID,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'RUNNING',
    operation TEXT NOT NULL,
    chunks_created INTEGER NOT NULL DEFAULT 0,
    result_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_ingestion_runs PRIMARY KEY (ingestion_run_id)
);

COMMIT;
