BEGIN;

-- R1 and R2 automation execution lifecycle.
CREATE TABLE ops.automation_runs (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    robot TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'RUNNING',
    result_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_automation_runs PRIMARY KEY (run_id)
);

-- R1 intake records; R1-only ownership remains application-enforced.
CREATE TABLE ops.incoming_emails (
    email_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_id BIGINT NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ,
    sender TEXT NOT NULL,
    recipient TEXT NOT NULL,
    subject TEXT,
    attachment_count INTEGER NOT NULL DEFAULT 0,
    sender_status TEXT NOT NULL DEFAULT 'PENDING',
    processing_status TEXT NOT NULL DEFAULT 'RECEIVED',
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_incoming_emails PRIMARY KEY (email_id)
);

-- Attachment metadata associated with an incoming email.
CREATE TABLE ops.email_attachments (
    attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email_id BIGINT NOT NULL,
    file_name TEXT NOT NULL,
    file_type TEXT,
    received_at TIMESTAMPTZ NOT NULL,
    validation_status TEXT NOT NULL DEFAULT 'PENDING',
    validation_message TEXT,
    establishment_count INTEGER,
    processing_status TEXT NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_email_attachments PRIMARY KEY (attachment_id)
);

-- Protocol ownership created by R1 and reused by subsequent R2 work.
CREATE TABLE ops.service_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    protocol_number TEXT NOT NULL,
    email_id BIGINT NOT NULL,
    r1_run_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'CREATED',
    result TEXT,
    failure_reason TEXT,
    completed_at TIMESTAMPTZ,
    return_email_at TIMESTAMPTZ,
    CONSTRAINT pk_service_requests PRIMARY KEY (request_id)
);

-- Current per-establishment operational state and R1-to-R2 handoff key.
CREATE TABLE ops.establishments (
    establishment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_id BIGINT NOT NULL,
    attachment_id BIGINT NOT NULL,
    establishment_number TEXT NOT NULL,
    generated_file_name TEXT NOT NULL,
    processing_status TEXT NOT NULL DEFAULT 'PENDING',
    upload_status TEXT NOT NULL DEFAULT 'PENDING',
    upload_at TIMESTAMPTZ,
    download_status TEXT NOT NULL DEFAULT 'NOT_AVAILABLE',
    download_at TIMESTAMPTZ,
    return_email_at TIMESTAMPTZ,
    result_message TEXT,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_establishments PRIMARY KEY (establishment_id)
);

-- Immutable chronological operational history with optional entity correlation.
CREATE TABLE ops.execution_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_id BIGINT NOT NULL,
    logged_at TIMESTAMPTZ NOT NULL,
    robot TEXT NOT NULL,
    event TEXT NOT NULL,
    status TEXT NOT NULL,
    message TEXT NOT NULL,
    email_id BIGINT,
    attachment_id BIGINT,
    request_id BIGINT,
    establishment_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_execution_log PRIMARY KEY (log_id)
);

COMMIT;
