BEGIN;

-- Sanitized security and governance evidence; no raw payload storage.
CREATE TABLE audit.security_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    event_type TEXT NOT NULL,
    source_component TEXT NOT NULL,
    user_identifier TEXT,
    request_reference TEXT,
    resource_category TEXT,
    sanitized_content TEXT,
    action_taken TEXT NOT NULL,
    result TEXT NOT NULL,
    review_status TEXT NOT NULL DEFAULT 'UNREVIEWED',
    reviewed_at TIMESTAMPTZ,
    review_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_security_events PRIMARY KEY (event_id)
);

COMMIT;
