# Generated by Django 6.1.1 on 2026-09-24 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WAITING_HUMAN', 'Waiting for human support'), ('HUMAN', 'Human support'), ('CLOSED', 'Closed'), ('BLOCKED', 'Blocked'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('status_before_block', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_conversations', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ('-updated_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent'), ('SUPPORT_AGENT', 'Support agent'), ('SYSTEM', 'System')], max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=12)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='conversations.conversation')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_portal_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['owner', 'status', '-updated_at'], name='idx_portal_conv_owner_status'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('ACTIVE', 'WAITING_HUMAN', 'HUMAN', 'CLOSED', 'BLOCKED', 'DELETED'))), name='ck_portal_conversations__status_allowed'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'BLOCKED'), ('status_before_block__in', ('ACTIVE', 'WAITING_HUMAN', 'HUMAN')), ('status_before_block__isnull', False)), models.Q(models.Q(('status', 'BLOCKED'), _negated=True), ('status_before_block__isnull', True)), _connector='OR'), name='ck_portal_conversations__block_state_consistent'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', False), ('deleted_by__isnull', False), ('status', 'DELETED')), models.Q(models.Q(('status', 'DELETED'), _negated=True), ('deleted_at__isnull', True), ('deleted_by__isnull', True)), _connector='OR'), name='ck_portal_conversations__deletion_consistent'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='ck_portal_conversations__title_nonblank'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at', 'id'], name='idx_portal_messages_conv_order'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('sender_type__in', ('CLIENT', 'AGENT', 'SUPPORT_AGENT', 'SYSTEM'))), name='ck_portal_messages__sender_allowed'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('idempotency_key__isnull', False), ('sender_type', 'CLIENT'), ('sender_user__isnull', False)), models.Q(('idempotency_key__isnull', True), ('sender_type', 'SUPPORT_AGENT'), ('sender_user__isnull', False)), models.Q(('idempotency_key__isnull', True), ('sender_type__in', ('AGENT', 'SYSTEM')), ('sender_user__isnull', True)), _connector='OR'), name='ck_portal_messages__sender_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('processing_status__in', ('PENDING', 'COMPLETED', 'FAILED'))), name='ck_portal_messages__processing_status_allowed'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='ck_portal_messages__body_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), ('sender_type', 'CLIENT')), fields=('conversation', 'idempotency_key'), name='uq_portal_messages__client_turn_idempotency'),
        ),
    ]
